### ISSUE TITLE
QGumboNode::getElementsByClassName

### ISSUE THREAD

**Issue by yuriio147** [lagner/QGumboParser#3]
In QGumboNode::getElementsByClassName
I think better to use 'strcmp' instead of 'strstr'.

**Comment by lagner** [comment]
We can not just use _strcmp_ instead of _strstr_ because they have different meaning. The point is gumbo_get_attribute returns all words in an attrubute value as a single string. 
For instance if you have a tag `<div class="Left date">date</div>` and request a value of _class_ attribute the gumbo returns _"Left date"_. Therefore we have to consider class name which you are looking for as a substring but not the whole value.

But you right, the solution was not good anyway. I have made this code a little bit better.
